import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./components/navbar/NavBar";
import Modal from "./components/modals/Modal";
import LoginModal from "./components/modals/LoginModal";
import SignUpModal from "./components/modals/SignUpModal";

const inter = Inter({ subsets: ["latin"] });

const content = () => {
  return (
    <p>This is a model test content</p>
  )
}

export const metadata: Metadata = {
  title: "BookNChill",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />  
        <div className="pt-32">
          {children}
        </div>
        <LoginModal />
        <SignUpModal />
      </body>
    </html>
  );
}
